services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.dev
    working_dir: /app
    container_name: restaurant-booking-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      PORT: "8080"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-restaurant_booking}
      REDIS_URL: redis://redis:6379/0
    networks:
      - restaurant-booking
    volumes:
      - ..:/app

  db:
    image: postgres:16-alpine
    restart: always
    container_name: restaurant-booking-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-restaurant_booking}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ../migrations:/migrations:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-restaurant_booking}"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    networks:
      - restaurant-booking

  redis:
    image: redis:alpine
    restart: always
    container_name: restaurant-booking-redis
    networks:
      - restaurant-booking

volumes:
  dbdata:
    name: restaurant_booking_dbdata

networks:
  restaurant-booking:
    driver: bridge
